<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>HollowKnightTAS.ClockInjector</AssemblyName>
    <RootNamespace>HollowKnightTAS.ClockInjector</RootNamespace>
  </PropertyGroup>
</Project>
